In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_rows=125

In [2]:
df=pd.read_csv('Minneapolis Open Data/Weather Data.csv')

/Users/simon/opt/anaconda3/envs/ds785/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (30,31,41,42,43,46,49,51,55,69,71,73,74,75,88,89) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.columns

Index(['STATION', 'DATE', 'REPORT_TYPE', 'SOURCE', 'AWND', 'BackupDirection',
       'BackupDistance', 'BackupDistanceUnit', 'BackupElements',
       'BackupElevation',
       ...
       'ShortDurationPrecipitationValue060',
       'ShortDurationPrecipitationValue080',
       'ShortDurationPrecipitationValue100',
       'ShortDurationPrecipitationValue120',
       'ShortDurationPrecipitationValue150',
       'ShortDurationPrecipitationValue180', 'Sunrise', 'Sunset', 'TStorms',
       'WindEquipmentChangeDate'],
      dtype='object', length=124)

In [4]:
df=df[['DATE', 'DailyMaximumDryBulbTemperature','DailyAverageDryBulbTemperature']]

In [5]:
df=df[pd.notnull(df.DailyMaximumDryBulbTemperature)]

In [6]:
df.DATE.nunique()

3400

In [7]:
df.dtypes

DATE                               object
DailyMaximumDryBulbTemperature    float64
DailyAverageDryBulbTemperature    float64
dtype: object

In [8]:
df['DATE']=pd.to_datetime(df.DATE)

In [9]:
df.groupby([df.DATE.dt.month,df.DATE.dt.year]).aggregate('mean')

           DailyMaximumDryBulbTemperature  DailyAverageDryBulbTemperature
DATE DATE
1    2011                       18.290323                       12.258065
     2012                       30.774194                       23.516129
     2013                       25.000000                       17.129032
     2014                       18.419355                        8.000000
     2015                       25.741935                       19.258065
     2016                       24.096774                       17.677419
     2017                       27.096774                       21.129032
     2018                       24.838710                       16.774194
     2019                       21.774194                       14.419355
     2020                       27.290323                       20.741935
2    2011                       26.964286                       18.964286
     2012                       34.827586                       28.034483
     2013                       26.178571                       19.250000
     2014                       17.500000                        8.821429
     2015                       19.464286                       11.321429
     2016                       31.793103                       25.137931
     2017                       40.178571                       31.464286
     2018                       25.071429                       16.178571
     2019                       21.178571                       13.035714
     2020                       29.827586                       21.413793
3    2011                       37.419355                       29.677419
     2012                       57.548387                       48.612903
     2013                       34.645161                       27.387097
     2014                       33.935484                       25.741935
     2015                       45.322581                       35.774194
     2016                       49.354839                       41.516129
     2017                       42.096774                       34.193548
     2018                       40.290323                       32.677419
     2019                       37.193548                       28.709677
     2020                       45.225806                       37.838710
4    2011                       55.133333                       46.433333
     2012                       59.566667                       50.266667
     2013                       48.600000                       41.233333
     2014                       51.433333                       42.933333
     2015                       59.866667                       49.966667
     2016                       56.900000                       48.300000
     2017                       59.300000                       50.733333
     2018                       47.400000                       37.733333
     2019                       55.200000                       46.366667
     2020                       53.120000                       43.120000
5    2011                       67.193548                       58.612903
     2012                       73.548387                       63.967742
     2013                       67.645161                       58.548387
     2014                       67.838710                       58.806452
     2015                       68.548387                       59.451613
     2016                       71.161290                       61.580645
     2017                       67.709677                       58.774194
     2018                       78.354839                       68.032258
     2019                       65.387097                       55.903226
6    2011                       78.733333                       69.766667
     2012                       82.333333                       72.500000
     2013                       77.066667                       69.066667
     2014                       77.966667                       69.700000
     2015                       78.666667                       69.966667
     2016                       80.533333                       71.533333
     2017                       81.333333                       71.600000
     2018                       80.866667                       72.933333
     2019                       79.233333                       70.033333
7    2011                       87.870968                       78.967742
     2012                       89.903226                       80.322581
     2013                       84.000000                       75.129032
     2014                       80.580645                       71.774194
     2015                       82.419355                       73.548387
     2016                       83.967742                       75.419355
     2017                       84.806452                       75.580645
     2018                       84.161290                       75.225806
     2019                       83.774194                       75.516129
8    2011                       82.387097                       73.903226
     2012                       82.096774                       72.225806
     2013                       84.161290                       75.000000
     2014                       81.806452                       73.548387
     2015                       79.258065                       71.000000
     2016                       81.903226                       73.580645
     2017                       77.032258                       68.935484
     2018                       82.903226                       74.193548
     2019                       79.419355                       71.258065
9    2011                       72.533333                       63.133333
     2012                       76.200000                       64.166667
     2013                       77.100000                       67.466667
     2014                       72.166667                       62.966667
     2015                       76.400000                       68.133333
     2016                       74.000000                       66.366667
     2017                       76.966667                       67.533333
     2018                       73.300000                       65.400000
     2019                       74.733333                       66.866667
10   2011                       64.903226                       55.612903
     2012                       56.354839                       47.741935
     2013                       57.096774                       49.354839
     2014                       58.354839                       49.419355
     2015                       61.032258                       52.387097
     2016                       61.161290                       53.161290
     2017                       59.548387                       51.580645
     2018                       53.290323                       46.096774
     2019                       53.161290                       46.258065
11   2011                       46.966667                       39.466667
     2012                       45.633333                       37.400000
     2013                       41.133333                       33.400000
     2014                       32.366667                       25.700000
     2015                       49.033333                       41.566667
     2016                       51.966667                       44.266667
     2017                       42.133333                       34.300000
     2018                       34.100000                       28.466667
     2019                       36.300000                       31.066667
12   2011                       34.133333                       27.800000
     2012                       30.580645                       23.580645
     2013                       20.633333                       13.166667
     2014                       30.200000                       25.266667
     2015                       35.129032                       30.451613
     2016                       26.967742                       21.161290
     2017                       25.225806                       19.032258
     2018                       31.645161                       26.064516
     2019                       30.354839                       23.419355

In [10]:
df=df.set_index('DATE')

In [11]:
df['threeDayAvgMaxWeather']=df.DailyMaximumDryBulbTemperature.rolling(3).mean()

In [12]:
df['weatherCalcDate']=df.index

In [13]:
df=df.shift(1).reset_index()

In [14]:
df=df.rename(columns={'DATE':'inspectionDate'})

In [15]:
df['inspectionDate']=pd.to_datetime(df.inspectionDate).dt.date

In [16]:
df=df[['inspectionDate','threeDayAvgMaxWeather']]

In [17]:
df

     inspectionDate  threeDayAvgMaxWeather
0        2011-01-01                    NaN
1        2011-01-02                    NaN
2        2011-01-03                    NaN
3        2011-01-04              15.666667
4        2011-01-05              15.666667
...             ...                    ...
3395     2020-04-21              59.000000
3396     2020-04-22              53.333333
3397     2020-04-23              59.000000
3398     2020-04-24              58.666667
3399     2020-04-25              64.000000

[3400 rows x 2 columns]

In [18]:
df.to_pickle('weather.pickle')